
development:
  adapter: postgresql
  encoding: unicode
  database: product-list_development
  pool: 5
  username: postgres
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: product-lis_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: product-lis_production
  pool: 5
  username: postgres
  password: