# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c5ff833aad59b4121cb774671fd9b0782adb4a2f8197a88e3aa3d3f6fcecbc3b9b2c24017fa2b3225c36ef1514f5432d5162f7f3507fd8b9def8f992266ec606

test:
  secret_key_base: dd226bacfe4ac48835d8e30546e59c3f04979fce9b0c0154d97164c6d4b35a098e7167951452f7342947957d0337b996769cba4567859453a951d46135d77506

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
